services:
  - type: web
    name: linebot
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AZURE_KEY
        sync: false
      - key: AZURE_ENDPOINT
        sync: false
      - key: WEATHER_API_KEY
        sync: false
